export const BRANCHES = [
  "B.Tech - CSE",
  "B.Tech - ECE",
  "B.Tech - EEE",
  "B.Tech - Mechanical",
  "B.Tech - Civil",
  "B.Tech - AI & ML",
  "B.Tech - Data Science",
  "B.Tech - Cyber Security",
  "B.Tech - Aerospace",
  "B.Tech - Biotechnology",
  "BBA",
  "BCA",
  "B.Com",
  "B.Des",
  "BA",
  "BSc",
  "MBA",
  "M.Tech",
];

export const HOME_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar Islands",
  "Chandigarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Jammu & Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const OTHER = "__other__";
