// B.Tech entries reflect only programs MIT Bengaluru actually offers (per the counseling.manipal.edu branch list).
export const BRANCHES = [
  "B.Tech - Computer Science & Engineering",
  "B.Tech - CSE (NZ Dual Degree, Auckland)",
  "B.Tech - Computer Science & Financial Technology",
  "B.Tech - Mathematics and Computing",
  "B.Tech - Electronics & Communication Engineering",
  "B.Tech - Electronics Engineering",
  "B.Tech - Robotics and Artificial Intelligence",
  "BBA",
  "BCA",
  "B.Com",
  "B.Des",
  "BA",
  "BSc",
  "MBA",
  "M.Tech",
];

export const HOME_STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman & Nicobar Islands",
  "Chandigarh",
  "Dadra & Nagar Haveli and Daman & Diu",
  "Delhi",
  "Jammu & Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
];

export const OTHER = "__other__";
